name: transformers
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py312hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py312hcf8288c_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - argcomplete==3.6.3
      - asgiref==3.11.0
      - attr==0.3.1
      - attrs==25.4.0
      - azure-core==1.36.0
      - azure-storage-blob==12.27.1
      - beautifulsoup4==4.14.2
      - black==25.11.0
      - bleach==5.0.1
      - boto==2.49.0
      - boto3==1.42.2
      - botocore==1.42.2
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - datamodel-code-generator==0.26.1
      - datasets==2.19.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - django==5.1.15
      - django-annoying==0.10.6
      - django-cors-headers==4.7.0
      - django-csp==3.7
      - django-debug-toolbar==3.2.1
      - django-environ==0.10.0
      - django-extensions==3.2.3
      - django-filter==24.3
      - django-migration-linter==5.2.0
      - django-model-utils==4.1.1
      - django-ranged-fileresponse==0.1.2
      - django-rq==2.10.3
      - django-storages==1.12.3
      - django-user-agents==0.4.0
      - djangorestframework==3.15.2
      - djangorestframework-simplejwt==5.5.1
      - dnspython==2.8.0
      - drf-dynamic-fields==0.3.0
      - drf-flex-fields==0.9.5
      - drf-generators==0.3.0
      - drf-spectacular==0.28.0
      - email-validator==2.3.0
      - expiringdict==1.2.2
      - faker==38.2.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.3.1
      - genson==1.3.0
      - google==3.0.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-appengine-logging==1.7.0
      - google-cloud-audit-log==0.4.0
      - google-cloud-core==2.5.0
      - google-cloud-logging==3.12.1
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - holidays==0.85
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ijson==3.4.0.post0
      - inflect==5.6.2
      - inflection==0.5.1
      - ipympl==0.9.8
      - ipywidgets==8.1.8
      - isodate==0.7.2
      - isort==5.13.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsf==0.11.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - label-studio==1.21.0
      - label-studio-sdk==2.0.4
      - launchdarkly-server-sdk==8.2.1
      - lightning-utilities==0.15.2
      - lockfile==0.12.2
      - lxml==6.0.2
      - lxml-html-clean==0.4.3
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - nbformat==5.10.4
      - networkx==3.5
      - nltk==3.9.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.14.1.1
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.9.79
      - openai==1.109.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.39.0
      - ordered-set==4.0.2
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==11.3.0
      - plotly==4.14.3
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - psycopg2-binary==2.9.10
      - pyarrow==18.1.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyboxen==1.3.0
      - pycocotools==2.0.10
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - pyrfc3339==2.1.0
      - python-json-logger==2.0.4
      - pytokens==0.3.0
      - pytz==2022.7.1
      - pyyaml==6.0.3
      - redis==5.2.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-file==3.0.1
      - requests-mock==1.12.1
      - retrying==1.4.2
      - rich==14.2.0
      - rpds-py==0.29.0
      - rq==1.16.2
      - rsa==4.9.1
      - rstr==3.2.2
      - rules==3.4
      - s3transfer==0.16.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - semver==3.0.4
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - simsimd==6.5.3
      - smart-open==7.5.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlparse==0.5.4
      - stringzilla==4.2.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tldextract==5.3.0
      - tokenizers==0.21.4
      - toml==0.10.2
      - torch==2.8.0+cu129
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu129
      - tqdm==4.67.1
      - transformers==4.51.0
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ua-parser==1.0.1
      - ua-parser-builtins==0.18.0.post1
      - ujson==5.11.0
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - user-agents==2.2.0
      - webencodings==0.5.1
      - wheel==0.40.0
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xmljson==0.2.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/miniconda3/envs/transformers
